sylius_admin_customer_set:
    resource: |
        alias: sylius.customer_set
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: sylius_admin_customer_set
        permission: true
        vars:
            all:
                header: sylius.ui.customer_set
                subheader: sylius.ui.manage_customer_sets
                templates:
                    form: SyliusAdminBundle:CustomerSet:_form.html.twig
            index:
                icon: archive
    type: sylius.resource
